"""Add constraints

Revision ID: 3105cbbdfe95
Revises: 7eb676c1548c
Create Date: 2020-12-02 09:05:29.198253

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "3105cbbdfe95"
down_revision = "7eb676c1548c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "location", ["uuid"])
    op.create_unique_constraint(None, "location_product", ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "location_product", type_="unique")
    op.drop_constraint(None, "location", type_="unique")
    # ### end Alembic commands ###
