"""Initial migration.

Revision ID: 7eb676c1548c
Revises: 
Create Date: 2020-11-25 16:43:44.112370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7eb676c1548c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("address_line_1", sa.String(), nullable=True),
        sa.Column("address_line_2", sa.String(), nullable=True),
        sa.Column("address_line_3", sa.String(), nullable=True),
        sa.Column("address_line_4", sa.String(), nullable=True),
        sa.Column("locality", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("location_type", sa.String(), nullable=True),
        sa.Column("ods_code", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["location.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_location_ods_code"), "location", ["ods_code"], unique=True)
    op.create_table(
        "location_product",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("product_name", sa.String(), nullable=False),
        sa.Column("opened_date", sa.Date(), nullable=False),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("location_uuid", sa.String(), nullable=True),
        sa.Column("closed_reason", sa.String(), nullable=True),
        sa.Column("closed_reason_other", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_uuid"],
            ["location.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location_product")
    op.drop_index(op.f("ix_location_ods_code"), table_name="location")
    op.drop_table("location")
    # ### end Alembic commands ###
