@startuml

skinparam defaultFontName Courier

Class Location {
    VARCHAR[36]       ★ uuid                
    VARCHAR[36]       ☆ parent_id           
    BOOLEAN           ⚪ active              
    VARCHAR           ⚪ address_line_1      
    VARCHAR           ⚪ address_line_2      
    VARCHAR           ⚪ address_line_3      
    VARCHAR           ⚪ address_line_4      
    VARCHAR           ⚪ country             
    DATETIME          ⚪ created             
    VARCHAR           ⚪ created_by_         
    VARCHAR           ⚪ display_name        
    VARCHAR           ⚪ locality            
    VARCHAR           ⚪ location_type       
    DATETIME          ⚪ modified            
    VARCHAR           ⚪ modified_by_        
    VARCHAR           ⚪ ods_code            
    VARCHAR           ⚪ postcode            
    VARCHAR           ⚪ region              
    VARCHAR           ⚪ score_system_default
    +                 children              
    +                 dh_products           
    +                 parent                
    to_compact_dict()                       
    to_dict()                               
    update()                                
    INDEX[ods_code]   » ix_location_ods_code
}

Class LocationProduct {
    VARCHAR[36]       ★ uuid               
    VARCHAR[36]       ☆ location_uuid      
    DATE              ⚪ closed_date        
    VARCHAR           ⚪ closed_reason      
    VARCHAR           ⚪ closed_reason_other
    DATETIME          ⚪ created            
    VARCHAR           ⚪ created_by_        
    DATETIME          ⚪ modified           
    VARCHAR           ⚪ modified_by_       
    DATE              ⚪ opened_date        
    VARCHAR           ⚪ product_name       
    +                 location             
    to_compact_dict()                      
    to_dict()                              
    update()                               
}

Location <--o Location: parent_id

LocationProduct <--o Location: location_uuid

right footer generated by sadisplay v0.4.9

@enduml
